on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: publish

jobs:
  release:
    name: release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      # this is cheaper than requesting the non-minimal profile
      - run: rustup component add rustfmt
      - run: rustup component add clippy

      - name: configure git / crates.io login
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          cargo login "$CRATES_TOKEN"
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}

      - name: publish
        run: cargo release --no-confirm --skip-push patch

      - name: publish git tag
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
